### ISSUE TITLE
Replacing bad HTML entities

### ISSUE THREAD

**Issue by jtl3d** [rwitzel/streamflyer#11]
My XML file is large so I read it with a FileInputSteam and pass to an XMLEventReader, but it's choking when I try to read the text content of a StartTag event that has `&#x16;` in it. I tried to use the createInvalidXmlCharacterReplacingReader() method, but I'm still getting the error. How could I use streamflyer to replace characters like `&#x16;`?

**Comment by rwitzel** [comment]
Do I understand correctly, that the file contains the character sequence &#x16; (i.e. an escaped character) instead of character \u0016 ?

In this case I'd just use the RegexModifier to replace "&#x16;" with something else, e.g. an empty string.

**Comment by jtl3d** [comment]
You are correct - it is not \u0016 but the actual string `&#x16;`, and the XMLEventReader doesn't like it. I decided to keep the modifying reader from createInvalidXmlCharacterReplacingReader() for good measure, and just added a RegexModifier to it before passing that reader to the XMLEventReader. I simply replace `&#` with `&amp;#` and it works like a charm now!

Thanks for your help, and a great, easy-to-use tool!
