### ISSUE TITLE
Can this library be used to do partial matches?

### ISSUE THREAD

**Issue by gbmhunter** [rwitzel/streamflyer#7]
I am trying to recognise ANSI escape sequences in an incoming stream of text from a serial port. Is this library suitable for this?

The problem I have with using the normal regex methods in Java is when the start of a ANSI escape sequence arrives at one point in time, but the reset of it comes in, say, 1 second later. I need to see if the first sequence of characters has a partial match, and find a what point the partial match starts. Java regex has a `hitEnd()` method, but does not tell you at where this match starts.

**Comment by rwitzel** [comment]
I guess it is not suitable.
